spring.application.name=minibilling

spring.datasource.url=jdbc:postgresql://localhost:5432/minibilling_v2
spring.datasource.username=postgres
spring.datasource.password=19062004
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
billing.output.dir=C:/outputdir/

app.admin.username=admin
app.admin.password=password
app.user.username=user
app.user.password=password